# Generated by Django 3.1.7 on 2021-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaUser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/imagenes/pawsse_paw.png', null=True, upload_to='images/'),
        ),
    ]
