# Generated by Django 3.1.7 on 2021-04-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20210414_0016'),
        ('instaUser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='post_app.ImageModel'),
        ),
    ]
