# Generated by Django 3.1.7 on 2021-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_remove_imagemodel_likes'),
        ('instaUser_app', '0002_auto_20210408_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='post_app.ImageModel'),
        ),
    ]
