# Generated by Django 3.1.7 on 2021-04-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='likes',
        ),
    ]
