# Generated by Django 3.1.7 on 2021-04-14 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
