# Generated by Django 3.1.7 on 2021-04-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20210409_1746'),
        ('post_app', '0002_auto_20210409_0333'),
    ]

    operations = [
    ]
