# Generated by Django 3.1.7 on 2021-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_merge_20210412_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
