# Generated by Django 3.1.7 on 2021-04-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20210414_1721'),
        ('post_app', '0003_merge_20210412_1807'),
    ]

    operations = [
    ]
